# OpenJDK 17 기반 이미지 사용
FROM openjdk:17-jdk-slim

# 작업 디렉토리 설정
WORKDIR /app

# Jar 파일 복사 (빌드 후 생긴 JAR 파일을 컨테이너 내부로 이동)
COPY build/libs/idempotent.jar idempotent.jar

# 컨테이너 실행 시 애플리케이션 실행
CMD ["java", "-jar", "idempotent.jar"]